# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - dev
 paths:
    include:
     - ledger_api/*
     - ledger_ui/* 
  
pool:
  name: 'MyHomeLab'

stages:
  - stage: Build_Backend
    displayName: 'Build and Test Backend'
    jobs:
     - job: FastAPI_Build
       steps:
         - script: |
            cd ledger_api
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
           displayName: 'Install Dependencies'
         - script: |
            cd ledger_api
            source venv/bin/activate
            alembic upgrade head --sql > migration.sql
           displayName: 'Generate SQL Migration Script'
           continueOnError: true
         - task: PublishBuildArtifacts@1
           inputs:
             PathtoPublish: 'ledger_api'
             ArtifactName: 'ledger_api-artifact'
             publishLocation: Container