# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - dev
 paths:
    include:
     - ledger_api/*
     - ledger_ui/* 
  
pool:
  name: 'MyHomeLab'

stages:
  - stage: Build_Backend
    displayName: 'Build and Test Backend'
    jobs:
     - job: FastAPI_Build
       steps:
         - script: |
            cd ledger_api
            python3 -m venv venv
            source venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
           displayName: 'Install Dependencies'
         - script: |
            cd ledger_api
            source venv/bin/activate
            alembic upgrade head --sql > migration.sql
           displayName: 'Generate SQL Migration Script'
           continueOnError: true
         - task: PublishBuildArtifacts@1
           inputs:
             PathtoPublish: 'ledger_api'
             ArtifactName: 'ledger_api-artifact'
             publishLocation: Container
  - stage: BuildReact
    displayName: 'Build React Frontend'
    dependsOn: []
    jobs:
     - job: React_Build
       steps:
         - task: NodeTool@0
           inputs:
            versionSpec: '18.x'
           displayName: 'Install Node.js'
         - script: |
            cd ledger_ui
            npm ci
            npm run build
           displayName: 'npm install and build'
         - task: PublishBuildArtifacts@1
           inputs:
             PathtoPublish: 'ledger_ui/dist'
             ArtifactName: 'react-build'
             publishLocation: 'Container'